const data = {
  products2: [
    {
      _id: "1",
      name: "Food Item 1",
      price: "200",
      quantity: "50",
      description: "test description.test description.",
      category: "lunch",
      // image: 'https://picsum.photos/id/180/2400/1600',
    },
    {
      _id: "2",
      name: "Food Item 2",
      price: "400",
      description: "test description.test description.",
      category: "breakfast",
      // image: 'https://picsum.photos/id/111/4400/2656',
    },
    {
      _id: "3",
      name: "Food Item 3",
      price: "500",
      description: "test description.test description.",
      category: "tea",
      // image: 'https://picsum.photos/id/21/3008/2008',
    },
    {
      _id: "4",
      name: "Food Item 4",
      price: "200",
      description: "test description.test description.",
      category: "lunch",
      // image: 'https://picsum.photos/id/21/3008/2008',
    },
    {
      _id: "5",
      name: "Food Item 5",
      price: "450",
      description: "test description.test description.",
      category: "tea",
      // image: 'https://picsum.photos/id/21/3008/2008',
    },
    {
      _id: "6",
      name: "Food Item 6",
      price: "120",
      description: "test description.test description.",
      category: "tea",
      // image: 'https://picsum.photos/id/21/3008/2008',
    },
    {
      _id: "627530e2db941d048030b0ed",
      name: "hoppers",
      price: "100",
      // quantity: "23",
      description: "hoppers are made with rice flour",
      category: "Breakfast",
      __v: 0,
    },
    {
      _id: "627796385514340afca6af60",
      name: "test",
      price: "450",
      // quantity: "4",
      description: "asd",
      category: "lunch",
      __v: 0,
    },
    {
      _id: "6277a39f5514340afca6af74",
      name: "dad",
      price: "45",
      // quantity: "5",
      description: "sdfsdfsdf",
      category: "lunch",
      __v: 0,
    },
    {
      _id: "6277a908a63743bdc1ef7d61",
      name: "Biriyani (C)",
      price: "100",
      // quantity: "2",
      description: "Biriyani rice with fried egg , minchi sambol and moju",
      category: "Lunch",
      __v: 0,
    },
    {
      _id: "6277b123c4c662c747d0618e",
      name: "as",
      price: "34",
      // quantity: "234",
      description: "dfgdg",
      category: "Breakfast",
      __v: 0,
    },
  ],
};

export default data;
